apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 3a7jouokyffroregistry.azurecr.io/ebhanda/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueForm:
                secretKeyRef:
                  name: db-url
                  key: url
      imagePullSecrets:
        - name: docker-pull-secret
